dist: bionic
language:
  cpp
compiler:
  - gcc
script:
    - rm -f build
    - rm -f bw-output
    - mkdir build
    - cd build
    - cmake
    - build-wrapper-linux-x86-64 --out-dir ../bw-output cmake
    - cd ..
    - sonar-scanner
    - -Dsonar.cfamily.build-wrapper-output=bw-output






addons:
  sonarcloud:
    organization: "brayan-00"
    token:
      secure: "81e64ec5ba629f55d7aa15a256e2dc16fb4c55a3"

