dist: bionic
language:
  cpp
compiler:
  - gcc
script:
    - rm -f build
    - rm -f bw-output
    - mkdir build
    - cd build
    - cmake
    - build-wrapper-linux-x86-64 --out-dir ../bw-output cmake
    - cd ..
    - sonar-scanner
      -Dsonar.organization=brayan-00
      -Dsonar.projectKey=Brayan-00_cpp_ci_pipeline
      -Dsonar.sources=.
      -Dsonar.host.url=https://sonarcloud.io
      -Dsonar.cfamily.build-wrapper-output=bw-output
      -Dsonar.login=088732ffb1eeb3e2b6d6a0a2cac299a699243b69


addons:
  sonarcloud:
    organization: "brayan-00"
    token:
      secure: "81e64ec5ba629f55d7aa15a256e2dc16fb4c55a3"

