language:
  cpp
compiler:
  - gcc
  - clang
script:
  - cmake
  - make clean
      # Wraps the compilation with the Build Wrapper to generate configuration (used
      # later by the SonarQube Scanner) into the "bw-output" folder
      - build-wrapper-linux-x86-64 --out-dir bw-output make all
      # Execute some tests
      - make test
      # And finally run the SonarQube analysis - read the "sonar-project.properties"
      # file to see the specific configuration
      - sonar-scanner

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      -

sonarcloud:
  organization: "sonarcloud"
  token:
    Brayan-00_cpp_ci_pipeline


cache:
  directories:
    - '$HOME/.sonar/cache'
